<a href="https://colab.research.google.com/github/Tonnonssi/study_LinearAlgebra/blob/main/01.%20Gaussian%20Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 Gaussian Elimination

In [44]:
import numpy as np

def find_1strow(column):
    column = abs(column)
    return np.min(column[np.nonzero(abs(column))])

def gaussian_elimination(matrix):
    process = ''
    matrix = matrix.astype(np.float64)
    
    process += 'Input matrix\n'
    process += '--------------------------------\n'
    process += str(matrix)+'\n\n'

    nrows, ncols = matrix.shape

    # search homogeneous linear system 
    if (matrix[:,-1] == np.zeros(nrows)).all() and nrows < (ncols - 1):       
        process += 'Answer\n'
        process += '--------------------------------\n'
        process += 'infinitely many solutions'
        return process

    # Perform Gaussian elimination
    process += 'Process\n'
    process += '--------------------------------\n'

    for i in range(nrows):

        if (matrix[i,:-1] == np.zeros((1,ncols-1))).all(): #REF을 만들면서 맨 마지막 행이 상수를 제외하고 전부 0이 될 때, 연산을 끝내기 위해
            break

        pivot = matrix[i, i]

        if pivot == 0:            
            min_num = find_1strow(matrix[:,i])
            nrow = np.where(matrix[:,i] == min_num) #tuple
            nrow = int(nrow[0])
            matrix[i], matrix[nrow] = matrix[nrow].copy(), matrix[i].copy()
            pivot = matrix[i, i]

        matrix[i, :] /= pivot
        for j in range(i+1, nrows):
            matrix[j, :] -= matrix[j, i] * matrix[i, :]

        process += str(matrix)+'\n\n'

    ### Back substitution

    for i in range(nrows): # no solution의 경우 탐색 
        if (matrix[i,:-1] == np.zeros(ncols-1)).all() and matrix[-1,-1] != 0:
            process += 'Answer\n'
            process += '--------------------------------\n'
            process += 'no solution'
            return process
            break

    # infinitely many solutions 탐색 
    int_nrows = nrows

    for i in range(nrows-1,0,-1): # no solution의 경우 탐색 
        if (matrix[i,:] == np.zeros(ncols)).all():
            int_nrows -= 1
        else:
            break

    if int_nrows < ncols-1:
        process += 'Answer\n'
        process += '--------------------------------\n'
        process += 'infinitely many solutions'
        return process        

    ans = np.zeros(ncols-1)

    point =  ncols - 2
    while point >= 0:
        for row in matrix[::-1]: 
            ans[point] += row[-1]
            for i in range(ncols-2,-1,-1):
                if i != point:
                    ans[point] -= row[i]*ans[i]
            point -= 1

    process += 'Answer\n'
    process += '--------------------------------\n'
    process += str(ans)

    return process

## 01's Test codes

In [45]:
arr = np.array([[0, 1, -1, 0],[1, 0, -3,-1],[-1, 3, 0, 1]])
print(gaussian_elimination(arr))

Input matrix
--------------------------------
[[ 0.  1. -1.  0.]
 [ 1.  0. -3. -1.]
 [-1.  3.  0.  1.]]

Process
--------------------------------
[[ 1.  0. -3. -1.]
 [ 0.  1. -1.  0.]
 [ 0.  3. -3.  0.]]

[[ 1.  0. -3. -1.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  0.  0.]]

Answer
--------------------------------
infinitely many solutions


In [46]:
arr = np.array([[1,0,-3,-2],[3,1,-2,5],[2,2,1,4]]) # one solution
print(gaussian_elimination(arr))

Input matrix
--------------------------------
[[ 1.  0. -3. -2.]
 [ 3.  1. -2.  5.]
 [ 2.  2.  1.  4.]]

Process
--------------------------------
[[ 1.  0. -3. -2.]
 [ 0.  1.  7. 11.]
 [ 0.  2.  7.  8.]]

[[  1.   0.  -3.  -2.]
 [  0.   1.   7.  11.]
 [  0.   0.  -7. -14.]]

[[ 1.  0. -3. -2.]
 [ 0.  1.  7. 11.]
 [-0. -0.  1.  2.]]

Answer
--------------------------------
[ 4. -3.  2.]


In [47]:
arr = np.array([[1,-1,2,4], [1,0,1,6], [2,-3,5,4]]) # no solution
print(gaussian_elimination(arr))

Input matrix
--------------------------------
[[ 1. -1.  2.  4.]
 [ 1.  0.  1.  6.]
 [ 2. -3.  5.  4.]]

Process
--------------------------------
[[ 1. -1.  2.  4.]
 [ 0.  1. -1.  2.]
 [ 0. -1.  1. -4.]]

[[ 1. -1.  2.  4.]
 [ 0.  1. -1.  2.]
 [ 0.  0.  0. -2.]]

Answer
--------------------------------
no solution


In [48]:
arr = np.array([[1,-1,2,4],[1,0,1,6],[2,-3,5,4],[3,2,-1,1]]) # no solution
print(gaussian_elimination(arr))

Input matrix
--------------------------------
[[ 1. -1.  2.  4.]
 [ 1.  0.  1.  6.]
 [ 2. -3.  5.  4.]
 [ 3.  2. -1.  1.]]

Process
--------------------------------
[[  1.  -1.   2.   4.]
 [  0.   1.  -1.   2.]
 [  0.  -1.   1.  -4.]
 [  0.   5.  -7. -11.]]

[[  1.  -1.   2.   4.]
 [  0.   1.  -1.   2.]
 [  0.   0.   0.  -2.]
 [  0.   0.  -2. -21.]]

Answer
--------------------------------
no solution


In [49]:
arr = np.array([[1,-1,3,0],[2,1,3,0]])
print(gaussian_elimination(arr))

Input matrix
--------------------------------
[[ 1. -1.  3.  0.]
 [ 2.  1.  3.  0.]]

Answer
--------------------------------
infinitely many solutions


In [50]:
arr = np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12]])
print(gaussian_elimination(arr))

Input matrix
--------------------------------
[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]]

Process
--------------------------------
[[1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Answer
--------------------------------
infinitely many solutions
